import ballerina/http;
import ballerina/sql;
import ballerina/time;

listener http:Listener ep0 = new (9090);

// The API-facing schemas from openapi.yaml, generated by `bal openapi` then
// hand-filled below. Kept in this same file as the resources that implement
// them so the contract and its implementation stay next to each other.

public type NewExpense record {
    string merchant;
    string date;
    decimal total;
    string receiptFileName;
    string receiptContentType;
    # base64-encoded receipt file content
    string receiptData;
};

public type Expense record {
    string id;
    string merchant;
    string date;
    decimal total;
    string createdAt;
    # original uploaded file name
    string receiptFileName;
    # MIME type of the uploaded receipt file
    string receiptContentType;
};

public type ExpenseCreated record {|
    *http:Created;
    Expense body;
|};

public type ExpenseListResponse record {
    # total matching expenses
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    # sum of the total of every one of the caller's saved expenses
    decimal runningTotal;
    Expense[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};

function noValidSession() returns ErrorUnauthorized {
    return {body: {code: 401, message: "no valid session"}};
}

function expenseNotFound() returns ErrorNotFound {
    return {body: {code: 404, message: "no such expense for the caller"}};
}

function invalidExpense(string reason) returns ErrorBadRequest {
    return {body: {code: 400, message: reason}};
}

function toExpense(ExpenseRow row) returns Expense => {
    id: row.id,
    merchant: row.merchant,
    date: row.expenseDate,
    total: row.total,
    createdAt: time:utcToString(row.createdAt),
    receiptFileName: row.receiptFileName,
    receiptContentType: row.receiptContentType
};

service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    # Liveness check — public, reads no identity.
    #
    # + return - the service is up
    resource function get health() returns http:Ok {
        return http:OK;
    }

    # The caller's saved expenses, with a running total.
    #
    # + return - a page of the caller's own saved expenses, or a 401 with no
    #            valid session
    resource function get me/expenses(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns ExpenseListResponse|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return noValidSession();
        }
        GatewayCaller caller = callerResult;

        int boundedLimit = 'limit <= 0 ? 20 : 'limit;
        if boundedLimit > 100 {
            boundedLimit = 100;
        }
        int boundedOffset = offset < 0 ? 0 : offset;

        ExpensePage page = check listExpenses(caller.userId, boundedLimit, boundedOffset);
        Expense[] data = from ExpenseRow row in page.rows
            select toExpense(row);

        string? next = ();
        if boundedOffset + boundedLimit < page.count {
            next = string `/me/expenses?limit=${boundedLimit}&offset=${boundedOffset + boundedLimit}`;
        }
        string? previous = ();
        if boundedOffset > 0 {
            int previousOffset = boundedOffset - boundedLimit;
            previous = string `/me/expenses?limit=${boundedLimit}&offset=${previousOffset < 0 ? 0 : previousOffset}`;
        }

        return {
            count: page.count,
            next: next,
            previous: previous,
            runningTotal: page.runningTotal,
            data: data
        };
    }

    # Save a new expense with its receipt.
    #
    # + return - the saved expense, a 400 for invalid input, or a 401 with no
    #            valid session
    resource function post me/expenses(http:RequestContext ctx, @http:Payload NewExpense payload)
            returns ExpenseCreated|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return noValidSession();
        }
        GatewayCaller caller = callerResult;

        byte[]|string validated = validateNewExpense(payload);
        if validated is string {
            return invalidExpense(validated);
        }

        ExpenseRow saved = check insertExpense(caller.userId, payload, validated);
        return <ExpenseCreated>{body: toExpense(saved)};
    }

    # One of the caller's own saved expenses.
    #
    # + return - the saved expense, a 404 when it is not the caller's, or a
    #            401 with no valid session
    resource function get me/expenses/[string expenseId](http:RequestContext ctx)
            returns Expense|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return noValidSession();
        }
        GatewayCaller caller = callerResult;

        ExpenseRow|error row = getExpense(caller.userId, expenseId);
        if row is sql:NoRowsError {
            return expenseNotFound();
        }
        if row is error {
            return row;
        }
        return toExpense(row);
    }

    # The original receipt file for one of the caller's own expenses, in its
    # original content type.
    #
    # + return - the raw receipt file, a 404 when it is not the caller's, or a
    #            401 with no valid session
    resource function get me/expenses/[string expenseId]/receipt(http:RequestContext ctx)
            returns http:Response|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return noValidSession();
        }
        GatewayCaller caller = callerResult;

        ReceiptRow|error receipt = getReceipt(caller.userId, expenseId);
        if receipt is sql:NoRowsError {
            return expenseNotFound();
        }
        if receipt is error {
            return receipt;
        }
        http:Response response = new;
        response.setBinaryPayload(receipt.data, contentType = receipt.contentType);
        return response;
    }
}
